In [1]:
#Import libraries
from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt

#Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

#Cleaning the data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\jenin\anaconda3\envs\Python_Data_Project\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.sample(6)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
565908,Software Engineer,Senior IT Engineer,Egypt,via BeBee,Full-time,False,Egypt,2023-11-24 04:27:22,False,False,Egypt,NaN,NaN,NaN,StatsBomb,NaN,NaN
404024,Data Analyst,Data Analyst 2,"Sacramento, CA",via Indeed,Full-time,False,"California, United States",2023-02-23 18:01:00,False,True,United States,hour,NaN,33.954998,UC Davis Health,NaN,NaN
745203,Data Scientist,Data Scientist,"Lisbon, Portugal",via BeBee Portugal,Full-time,False,Portugal,2023-09-08 21:00:32,False,False,Portugal,NaN,NaN,NaN,Two Impulse,NaN,NaN
720277,Data Scientist,"Data Scientist, Growth and Marketing","Las Vegas, NV",via LinkedIn,Full-time,False,"California, United States",2023-09-11 21:01:01,False,False,United States,NaN,NaN,NaN,Dropbox,"['sql', 'r', 'python', 'hadoop', 'flow']","{'libraries': ['hadoop'], 'other': ['flow'], '..."
653931,Senior Data Engineer,Senior Backend Data Engineer,Anywhere,via LinkedIn,Full-time,True,Georgia,2023-03-10 11:03:18,False,False,United States,NaN,NaN,NaN,Shield AI,"['python', 'nosql', 'golang', 'git']","{'other': ['git'], 'programming': ['python', '..."
355884,Data Analyst,"[GOVT] Data Analyst, Customer Operations - JL",Singapore,via Jobrapido.com,Full-time,False,Singapore,2023-03-16 23:54:24,False,False,Singapore,NaN,NaN,NaN,BGC GROUP PTE. LTD.,['excel'],{'analyst_tools': ['excel']}

In [3]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
df.index.name = "Job Id"

In [5]:
df.index.dtype

dtype('int64')

In [6]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
Job Id,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [7]:
df_europe =df[df["job_location"] == "Germany"]

df_europe.reset_index(inplace=True)
df_europe.head(10)

,Job Id,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,1725,Data Engineer,Data Engineer SAP Reporting (m/w/d),Germany,via Indeed,Full-time,False,Germany,2023-11-06 14:09:43,True,False,Germany,NaN,NaN,NaN,Hays,"['sap', 'jira', 'confluence']","{'analyst_tools': ['sap'], 'async': ['jira', '..."
1,2177,Data Scientist,Data Scientist Kundendatenauswertung,Germany,via BeBee Deutschland,NaN,False,Germany,2023-02-02 13:20:13,False,False,Germany,NaN,NaN,NaN,Hays AG,['r'],{'programming': ['r']}
2,2618,Data Engineer,Remote: Data Engineers,Germany,via BeBee,"Full-time, Part-time, and Temp work",False,Germany,2023-11-03 13:13:20,False,False,Germany,NaN,NaN,NaN,Deutsche Bundesbank,"['hadoop', 'unix', 'linux', 'redhat']","{'libraries': ['hadoop'], 'os': ['unix', 'linu..."
3,2904,Data Engineer,Data Engineer (m/f/d),Germany,via LinkedIn,Full-time,False,Germany,2023-06-05 13:38:44,True,False,Germany,NaN,NaN,NaN,PARTSCLOUD GmbH,"['python', 'sql', 'postgresql', 'aws', 'react'...","{'cloud': ['aws'], 'databases': ['postgresql']..."
4,3099,Senior Data Scientist,Senior Data Scientist Remote,Germany,via BeBee,Full-time,False,Germany,2023-12-02 13:27:40,False,False,Germany,NaN,NaN,NaN,Deutsche Bahn AG,"['sql', 'spss']","{'analyst_tools': ['spss'], 'programming': ['s..."
5,3104,Data Scientist,Data Warehouse Specialist,Germany,via Jobs Trabajo.org,Full-time,False,Germany,2023-10-18 13:13:57,True,False,Germany,NaN,NaN,NaN,CompuSafe Data Systems,['sql'],{'programming': ['sql']}
6,3143,Data Analyst,Data Analyst in der Autovermietung / Business ...,Germany,via LinkedIn,Full-time,False,Germany,2023-11-20 13:17:04,True,False,Germany,NaN,NaN,NaN,Avis Budget Group,['excel'],{'analyst_tools': ['excel']}
7,3977,Data Analyst,Data Analyst (w/m/d),Germany,via Stepstone,Full-time,False,Germany,2023-06-23 13:31:55,True,False,Germany,NaN,NaN,NaN,Lenze SE,"['sql', 'sap', 'excel', 'dax']","{'analyst_tools': ['sap', 'excel', 'dax'], 'pr..."
8,4126,Cloud Engineer,Cloud Engineer,Germany,via BeBee,Full-time,False,Germany,2023-11-19 13:18:02,True,False,Germany,NaN,NaN,NaN,Capgemini,"['python', 'sql', 'bash', 'redshift', 'spark',...","{'cloud': ['redshift'], 'libraries': ['spark']..."
9,4427,Data Engineer,Data Engineer,Germany,via LinkedIn,Full-time,False,Germany,2023-08-24 13:42:39,False,False,Germany,NaN,NaN,NaN,Audi Interaction GmbH,"['sql', 'vba', 'oracle', 'sap', 'ms access', '...","{'analyst_tools': ['sap', 'ms access', 'excel'..."

In [8]:
df_europe.set_index("Job Id", inplace = True)

df_europe.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
Job Id,,,,,,,,,,,,,,,,,
1725,Data Engineer,Data Engineer SAP Reporting (m/w/d),Germany,via Indeed,Full-time,False,Germany,2023-11-06 14:09:43,True,False,Germany,NaN,NaN,NaN,Hays,"['sap', 'jira', 'confluence']","{'analyst_tools': ['sap'], 'async': ['jira', '..."
2177,Data Scientist,Data Scientist Kundendatenauswertung,Germany,via BeBee Deutschland,NaN,False,Germany,2023-02-02 13:20:13,False,False,Germany,NaN,NaN,NaN,Hays AG,['r'],{'programming': ['r']}
2618,Data Engineer,Remote: Data Engineers,Germany,via BeBee,"Full-time, Part-time, and Temp work",False,Germany,2023-11-03 13:13:20,False,False,Germany,NaN,NaN,NaN,Deutsche Bundesbank,"['hadoop', 'unix', 'linux', 'redhat']","{'libraries': ['hadoop'], 'os': ['unix', 'linu..."
2904,Data Engineer,Data Engineer (m/f/d),Germany,via LinkedIn,Full-time,False,Germany,2023-06-05 13:38:44,True,False,Germany,NaN,NaN,NaN,PARTSCLOUD GmbH,"['python', 'sql', 'postgresql', 'aws', 'react'...","{'cloud': ['aws'], 'databases': ['postgresql']..."
3099,Senior Data Scientist,Senior Data Scientist Remote,Germany,via BeBee,Full-time,False,Germany,2023-12-02 13:27:40,False,False,Germany,NaN,NaN,NaN,Deutsche Bahn AG,"['sql', 'spss']","{'analyst_tools': ['spss'], 'programming': ['s..."

In [9]:
Median_pivot = df_europe.pivot_table(index="job_title_short", values="salary_year_avg", aggfunc=["median", "max","min"])
Median_pivot

                                   median             max             min
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  80850.0         80850.0         80850.0
Cloud Engineer                    80850.0         80850.0         80850.0
Data Analyst                      91587.5        179500.0         56381.0
Data Engineer                    146000.0        146000.0        146000.0
Data Scientist                   120564.0        171121.0         90931.0
Machine Learning Engineer        166000.0        198000.0         49896.0
Senior Data Analyst              119400.0        119400.0        119400.0
Senior Data Engineer             147500.0        155500.0        147500.0
Senior Data Scientist            147500.0        147500.0        147500.0
Software Engineer                158500.0        158500.0        158500.0

In [10]:
Median_pivot.sort_values(by= ('median', 'salary_year_avg'),ascending =True)

                                   median             max             min
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  80850.0         80850.0         80850.0
Cloud Engineer                    80850.0         80850.0         80850.0
Data Analyst                      91587.5        179500.0         56381.0
Senior Data Analyst              119400.0        119400.0        119400.0
Data Scientist                   120564.0        171121.0         90931.0
Data Engineer                    146000.0        146000.0        146000.0
Senior Data Engineer             147500.0        155500.0        147500.0
Senior Data Scientist            147500.0        147500.0        147500.0
Software Engineer                158500.0        158500.0        158500.0
Machine Learning Engineer        166000.0        198000.0         49896.0

In [11]:
Median_pivot.sort_index(inplace=True)

In [12]:
Median_pivot

                                   median             max             min
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  80850.0         80850.0         80850.0
Cloud Engineer                    80850.0         80850.0         80850.0
Data Analyst                      91587.5        179500.0         56381.0
Data Engineer                    146000.0        146000.0        146000.0
Data Scientist                   120564.0        171121.0         90931.0
Machine Learning Engineer        166000.0        198000.0         49896.0
Senior Data Analyst              119400.0        119400.0        119400.0
Senior Data Engineer             147500.0        155500.0        147500.0
Senior Data Scientist            147500.0        147500.0        147500.0
Software Engineer                158500.0        158500.0        158500.0